"""fix finance models, add system_settings and audit_logs

Revision ID: 616148e27a8d
Revises: 586307cc756f
Create Date: 2026-09-15 17:49:07.440055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616148e27a8d'
down_revision: Union[str, Sequence[str], None] = '586307cc756f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_resource_type', 'audit_logs', ['resource_type'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_minus_beshming', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('consultations', 'minus_beshming',
               existing_type=sa.NUMERIC(precision=8, scale=0),
               type_=sa.Numeric(precision=12, scale=0),
               existing_nullable=True)
    # ### end Alembic commands ###

    # Hand-added: autogenerate doesn't diff CheckConstraints by default.
    op.create_check_constraint(
        'ck_surgeries_expense_non_negative',
        'surgeries',
        'surgery_expense >= 0',
    )

    # Hand-added: seed the singleton settings row so the app never has to
    # handle a missing-row case.
    op.execute(
        "INSERT INTO system_settings (id, default_minus_beshming, updated_at) "
        "VALUES (1, 5000, now())"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_surgeries_expense_non_negative', 'surgeries', type_='check')

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('consultations', 'minus_beshming',
               existing_type=sa.Numeric(precision=12, scale=0),
               type_=sa.NUMERIC(precision=8, scale=0),
               existing_nullable=True)
    op.drop_table('system_settings')
    op.drop_index('ix_audit_logs_resource_type', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
